version: '3.8'

services:  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Itbs@Dev123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-db.sql:/init-db.sql
      
  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlserver-init
    depends_on:
      - sqlserver
    volumes:
      - ./init-db.sql:/init-db.sql
    command: /bin/bash -c 'sleep 30 && /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P "Itbs@Dev123" -i /init-db.sql'
  
  maintenance-api:
    build: .
    container_name: maintenance-api
    depends_on:
      - sqlserver
      - sqlserver-init
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=maintenance_db;
      - SPRING_DATASOURCE_USERNAME=mohamed_fenina
      - SPRING_DATASOURCE_PASSWORD=Itbs@Dev123

volumes:
  sqlserver_data:
